export const BANKING_PROVIDERS = [
  {
    slug: 'bunq',
    name: 'Bunq',
    logo: 'B', logoColor: '#3344EE',
    rating: 4.5, reviewCount: 24800,
    monthlyFee: 2.99,
    features: [
      'Mobiele bank, 100% in app',
      '25 sub-rekeningen voor sparen',
      'Reizen zonder wisselkosten',
      'Boomplant-bonus per €100',
      '€20 startbonus via BespaarCheck',
    ],
    bonus: 20, bestChoice: true,
    welcomeBonus: { amount: 20, description: '€20 startbonus na eerste betaling', appliesAfter: 'signup' },
    affiliateLink: 'https://bunq.com/r/BESPAARCHECK',
    network: 'adtraction',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 14 },
  },
  {
    slug: 'revolut',
    name: 'Revolut',
    logo: 'R', logoColor: '#191C1F',
    rating: 4.3, reviewCount: 89000,
    monthlyFee: 0,
    features: [
      'Gratis basisrekening',
      'Goedkope valutawisseling',
      'Directe betaalverzoeken',
      'Uitgaven-analyse per categorie',
    ],
    bonus: 0, bestChoice: false,
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://revolut.com',
    network: 'direct',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 14 },
  },
  {
    slug: 'n26',
    name: 'N26',
    logo: 'N', logoColor: '#48AC98',
    rating: 4.1, reviewCount: 31200,
    monthlyFee: 0,
    features: [
      'Gratis basisrekening',
      'Tot 5 gratis opnames/mnd',
      'Budgetcategorieën',
      'Instant overboekingen',
    ],
    bonus: 0, bestChoice: false,
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://n26.com',
    network: 'direct',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 14 },
  },
  {
    slug: 'knab',
    name: 'Knab',
    logo: 'K', logoColor: '#FF5600',
    rating: 4.0, reviewCount: 8400,
    monthlyFee: 5.99,
    features: [
      'Volledige Nederlandse bank',
      'Uitstekende klantenservice',
      'Spaarrekening met rente',
      'Budgettool ingebouwd',
    ],
    bonus: 75, bestChoice: false,
    welcomeBonus: { amount: 75, description: '€75 cashback na 3 maanden', appliesAfter: 'first_3_months' },
    affiliateLink: 'https://knab.nl',
    network: 'adtraction',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 14 },
  },
]
