export const ENERGY_PROVIDERS = [
  {
    slug: 'vandebron',
    name: 'Vandebron',
    logo: 'V', logoColor: '#00A651',
    rating: 4.2, reviewCount: 12400,
    bestChoice: true,
    welcomeBonus: { amount: 100, description: '€100 welkomstkorting eerste jaar', appliesAfter: 'signup' },
    pricing: { fixedFee: 7.95, kwhRate: 0.27, m3Rate: 1.28, contractType: 'fixed_1yr' },
    regions: ['noord-holland','zuid-holland','utrecht','brabant','gelderland-oost','gelderland-west','overijssel','limburg'],
    features: ['100% groene stroom', 'Vaste tarieven 1 jaar', 'Directe overstap via ons'],
    contractDetails: { minimumDuration: 12, cancellationFee: 0, coolingOffDays: 14 },
    affiliateLink: 'https://vandebron.nl',
  },
  {
    slug: 'greenchoice',
    name: 'Greenchoice',
    logo: 'G', logoColor: '#79B829',
    rating: 4.0, reviewCount: 9800,
    bestChoice: false,
    welcomeBonus: { amount: 50, description: '€50 korting eerste rekening', appliesAfter: 'first_invoice' },
    pricing: { fixedFee: 8.50, kwhRate: 0.28, m3Rate: 1.30, contractType: 'fixed_1yr' },
    regions: ['noord-holland','zuid-holland','utrecht','brabant','gelderland-oost','gelderland-west','overijssel','limburg','noord'],
    features: ['100% Nederlandse groene stroom', 'Flexibel contract mogelijk', 'Duurzame coöperatie'],
    contractDetails: { minimumDuration: 12, cancellationFee: 25, coolingOffDays: 14 },
    affiliateLink: 'https://greenchoice.nl',
  },
  {
    slug: 'eneco',
    name: 'Eneco',
    logo: 'E', logoColor: '#FF6600',
    rating: 3.8, reviewCount: 28000,
    bestChoice: false,
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    pricing: { fixedFee: 9.95, kwhRate: 0.30, m3Rate: 1.38, contractType: 'variable' },
    regions: ['noord-holland','zuid-holland','utrecht','brabant','gelderland-oost','gelderland-west','overijssel','limburg','noord'],
    features: ['Groot energiebedrijf', 'Variabele tarieven', 'Slimme thuisoplossingen'],
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 14 },
    affiliateLink: 'https://eneco.nl',
  },
  {
    slug: 'essent',
    name: 'Essent',
    logo: 'E', logoColor: '#CC0000',
    rating: 3.7, reviewCount: 34000,
    bestChoice: false,
    welcomeBonus: { amount: 75, description: '€75 cashback na 6 maanden', appliesAfter: 'first_6_months' },
    pricing: { fixedFee: 9.50, kwhRate: 0.29, m3Rate: 1.35, contractType: 'fixed_1yr' },
    regions: ['noord-holland','zuid-holland','utrecht','brabant','gelderland-oost','gelderland-west','overijssel','limburg','noord'],
    features: ['Groot leverancier', '1 jaar vaste prijs', 'Online klantportaal'],
    contractDetails: { minimumDuration: 12, cancellationFee: 50, coolingOffDays: 14 },
    affiliateLink: 'https://essent.nl',
  },
]
