export const INSURANCE_PROVIDERS = [
  {
    slug: 'zilveren-kruis',
    name: 'Zilveren Kruis',
    logo: 'ZK', logoColor: '#004B87',
    rating: 4.0, reviewCount: 28000,
    bestChoice: true,
    monthlyHealth: 133,
    ownRiskOptions: [0, 100, 200, 300, 400, 500],
    features: ['Goede basis + aanvulling', 'Brede dekking tandarts', 'Snelle vergoeding'],
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://zilverenkruis.nl',
  },
  {
    slug: 'cz',
    name: 'CZ',
    logo: 'CZ', logoColor: '#00954E',
    rating: 3.9, reviewCount: 22000,
    bestChoice: false,
    monthlyHealth: 128,
    ownRiskOptions: [0, 100, 200, 300, 400, 500],
    features: ['Goede prijs-kwaliteit', 'Ruime aanvullingsopties', 'Eigen zorgcentra'],
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://cz.nl',
  },
  {
    slug: 'ditzo',
    name: 'Ditzo',
    logo: 'D', logoColor: '#FF5700',
    rating: 4.2, reviewCount: 9800,
    bestChoice: false,
    monthlyHealth: 119,
    ownRiskOptions: [0, 100, 200, 300, 400, 500],
    features: ['Laagste basispremie', 'Online aanvragen', 'Eerlijke uitleg zonder jargon'],
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://ditzo.nl',
  },
]
