export const TELECOM_PROVIDERS = [
  {
    slug: 'odido-internet',
    name: 'Odido',
    logo: 'O', logoColor: '#FF4500',
    rating: 4.1, reviewCount: 18200,
    bestChoice: true,
    monthlyTotal: 38,
    minSpeed: 100,
    features: ['100 Mbit internet', 'Geen activatiekosten', 'Gratis modem', '2 jaar vast tarief'],
    welcomeBonus: { amount: 50, description: '€50 cashback na 3 maanden', appliesAfter: 'first_3_months' },
    affiliateLink: 'https://odido.nl',
    contractDetails: { minimumDuration: 24, cancellationFee: 0, coolingOffDays: 14 },
  },
  {
    slug: 'kpn-internet',
    name: 'KPN',
    logo: 'K', logoColor: '#009DE0',
    rating: 3.9, reviewCount: 42000,
    bestChoice: false,
    monthlyTotal: 45,
    minSpeed: 100,
    features: ['100 Mbit glasvezel', 'TV-pakket optioneel', 'Landelijk netwerk', 'KPN App'],
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://kpn.com',
    contractDetails: { minimumDuration: 24, cancellationFee: 0, coolingOffDays: 14 },
  },
  {
    slug: 'ziggo-internet',
    name: 'Ziggo',
    logo: 'Z', logoColor: '#E4007C',
    rating: 3.7, reviewCount: 51000,
    bestChoice: false,
    monthlyTotal: 48,
    minSpeed: 500,
    features: ['500 Mbit standaard', 'Inclusief Ziggo Sport optie', 'WiFi Pods beschikbaar'],
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    affiliateLink: 'https://ziggo.nl',
    contractDetails: { minimumDuration: 24, cancellationFee: 0, coolingOffDays: 14 },
  },
]
