export const VPN_PROVIDERS = [
  {
    slug: 'nordvpn',
    name: 'NordVPN',
    logo: 'N', logoColor: '#4687FF',
    rating: 4.6, reviewCount: 142000,
    bestChoice: true,
    priceMonthly: 3.39,
    price: { monthly: 12.99, annual: 4.49, biennial: 3.39 },
    welcomeBonus: { amount: 0, description: '3 maanden gratis bij 2-jaar abonnement', appliesAfter: 'signup' },
    features: ['6680+ servers in 111 landen', 'Strikt no-logs beleid', '6 gelijktijdige apparaten', 'Threat Protection'],
    affiliateLink: 'https://nordvpn.com',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 30 },
  },
  {
    slug: 'surfshark',
    name: 'Surfshark',
    logo: 'S', logoColor: '#1DBFFF',
    rating: 4.4, reviewCount: 87000,
    bestChoice: false,
    priceMonthly: 2.49,
    price: { monthly: 12.95, annual: 3.99, biennial: 2.49 },
    welcomeBonus: { amount: 0, description: '2 maanden gratis bij 2-jaar abonnement', appliesAfter: 'signup' },
    features: ['Onbeperkte apparaten', '3200+ servers', 'CleanWeb ad-blocker', 'Camouflage modus'],
    affiliateLink: 'https://surfshark.com',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 30 },
  },
  {
    slug: 'expressvpn',
    name: 'ExpressVPN',
    logo: 'E', logoColor: '#DA3940',
    rating: 4.5, reviewCount: 98000,
    bestChoice: false,
    priceMonthly: 6.67,
    price: { monthly: 12.95, annual: 8.32, biennial: 6.67 },
    welcomeBonus: { amount: 0, description: '', appliesAfter: 'signup' },
    features: ['3000+ servers in 94 landen', 'Snelste verbinding', '5 apparaten', 'Lightway protocol'],
    affiliateLink: 'https://expressvpn.com',
    contractDetails: { minimumDuration: 0, cancellationFee: 0, coolingOffDays: 30 },
  },
]
